name: Run npm Command  

on:  
  workflow_dispatch:  # This allows manual triggering of the workflow  
  push:  
    branches:  
      - main  # Your specified branch  

jobs:  
  build:  
    runs-on: ubuntu-latest  

    steps:  
    - name: Checkout repository  
      uses: actions/checkout@v2  

    - name: Set up Node.js  
      uses: actions/setup-node@v2  
      with:  
        node-version: '14'  # Specify the Node.js version you want  

    - name: Install npm dependencies  
      run: npm install crypto crypto-js nodemailer

    - name: Run npm command  
      run: npm run your-command  # Replace with your actual npm command
