name: Run npm Command  

on:  
  workflow_dispatch:  # This allows manual triggering of the workflow  
  push:  
    branches:  
      - main  # Your specified branch  

jobs:  
  build:  
    runs-on: ubuntu-latest  

    steps:  
    - name: Checkout repository  
      uses: actions/checkout@v3  # Updated to version 3  

    - name: Set up Node.js  
      uses: actions/setup-node@v3  # Updated to version 3  
      with:  
        node-version: '18'  # You can choose a stable LTS version, e.g., 14, 16, or 18  

    - name: Install npm dependencies  
      run: npm install  

    - name: Run npm command  
      run: npm run your-command  # Replace with your actual npm command
