name: Run npm Command  

on:  
  workflow_dispatch:  # This allows manual triggering of the workflow  
  push:  
    branches:  
      - main  # Your specified branch  

jobs:  
  build:  
    runs-on: ubuntu-latest  

    steps:  
    - name: Checkout repository  
      uses: actions/checkout@v3  # Keep this up to date  

    - name: Set up Node.js  
      uses: actions/setup-node@v3  # Keep this up to date  
      with:  
        node-version: '20'  # Set this to Node.js 20 to align with current best practices  

    - name: Install npm dependencies  
      run: npm install crypto nodemailer

    - name: Run npm command  
      run: npm init -y  # Replace with your actual npm command
