name: Security Scan

on:
  schedule:
    - cron: '0 0 * * 0'  # Run weekly on Sundays at midnight
  workflow_dispatch:  # Allow manual trigger

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the website
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.4.0
        with:
          target: 'https://diadema-dti.netlify.app'
      - name: Upload ZAP Report
        uses: actions/upload-artifact@v2
        with:
          name: ZAP Scan Report
          path: report.html
